#!/usr/bin/env php
<?php

if (!defined('DS')) {
    define('DS', DIRECTORY_SEPARATOR);
}

if (!defined('SILEX_ENV')) {
    define('SILEX_ENV', 'dev');
}

if (!defined('SILEX_DEBUG')) {
    define('SILEX_DEBUG', false);
}

require_once __DIR__.DS.'bootstrap.php';

$app = createDefaultSilexApp(__DIR__, SILEX_ENV, SILEX_DEBUG);

use Spyrit\Silex\Utils\Command\CacheClearCommand;
use Symfony\Component\Console\Application as BaseApplication;

class Application extends BaseApplication
{
    const NAME = 'Silex Console Tool';
    const VERSION = '0.1';

    protected $projectDir;

    public function __construct()
    {
        parent::__construct(static::NAME, static::VERSION);
        $this->add(new CacheClearCommand());
        $this->projectDir = realpath(__DIR__.DS.'..');
    }

    public function getProjectDir()
    {
        return $this->projectDir;
    }

    public function getBinDir()
    {
        return $this->projectDir.DS.'bin';
    }
}

$console = new Application();
$console->run();